### ISSUE TITLE
How to use with AppEngine?

### ISSUE THREAD

**Issue by kno10** [googlesamples/identity-toolkit-python#8]
I cannot find a working example how to get the identity toolkit working with AppEngine.

Surprisingly, many of the required libraries do not appear to be preinstalled in AppEngine either, but require complicated "vendor" installation.

All identity-toolkit libraries should be preinstalled ("runtime provided") by Google App Engine:
https://cloud.google.com/appengine/docs/python/tools/libraries27

Previously reported as: https://github.com/google/identity-toolkit-python-client/issues/14

**Comment by wuyanna** [comment]
The vendor installation is inevitable since the preinstalled libs on Google App Engine are very limited. It's fairly common for App Engine apps to install third-party libs, and it only requires adding two lines of code: https://cloud.google.com/appengine/docs/python/tools/libraries27#vendoring
 
Unfortunately we don't have an official documentation for GAE support, but you can run this sample on GAE with a few modifications.

You will need to replace the `requirements.txt` with the following dependencies for it to work on GAE:
```
# This requirements file lists all third-party dependencies for this project.
#
# Run 'pip install -r requirements.txt -t lib/' to install these dependencies
# in `lib/` subdirectory.
#
# Note: The `lib` directory is added to `sys.path` by `appengine_config.py`.
Flask==0.10
identity-toolkit-python-client==0.1.11
pycrypto==2.6
```

Also add the following to the `libraries` section in your app.yaml file:
```
libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"
```

**Comment by paullj1** [comment]
Is there a "best practice" for referencing your private key?  The library chokes here:

File "/base/data/home/apps/s~milcyber-app2/1.391329219511608322/lib/identitytoolkit/gitkitclient.py", line 234, in FromConfigFile
    key_file = open(json_data['serviceAccountPrivateKeyFile'], 'rb')
IOError: [Errno 2] No such file or directory: u'/google_key.json'

**Comment by sthomp** [comment]
@paullj1 Im having this same issue. Did you figure out a solution?

**Comment by paullj1** [comment]
Sorry, no. We went a different route.

**Comment by kno10** [comment]
I have also moved away from identity toolkit, because I could not get it to work on Google AppEngine.
For my purpose, a simpler login is good enough. Too bad, Google does not provide preinstalled libraries to make this more usable.
